CREATE DATABASE $(CIVILAPP_DB);
GO
USE $(CIVILAPP_DB);
GO
CREATE LOGIN $(CIVILAPP_USER) WITH PASSWORD = '$(CIVILAPP_PASSWORD)';
GO
CREATE USER $(CIVILAPP_USER) FOR LOGIN $(CIVILAPP_USER);
GO
ALTER ROLE db_owner ADD MEMBER [$(CIVILAPP_USER)];
GO